//
//  Constants.swift
//  AnyMRZ
//
//  Created by Bohdan Mihiliev on 29.06.2019.
//  Copyright © 2019 Bohdan Mihiliev. All rights reserved.

let passportMRZLinesCount = 2
let uaeIDCardMRZLinesCount = 3
public let barCodeStringPayLoadKey = "barCodePayLoad"
public let MRZLinesPayLoadKey = "mrzLinesPayLoadKey"
public let mrzFieldNamesMap = [
  "dateOfExpiration": "Date of Expiration",
  "issuingCountryName": "Issuing Country Name",
  "firstRowOptional": "First Row Optional",
  "documentNumber": "Document number",
  "givenName": "Given Name",
  "firstName": "First Name",
  "lastName": "Last Name",
  "dateOfBirth": "Date of Birth",
  "gender": "Gender",
  "nationalityName": "Nationality",
  "nationalityCode": "Nationality Code",
  "secondRowOptional": "Second Row Optional",
  "countryCode": "Country Code",
  "countryName": "Country Name",
  "passportNumber": "Passport Name",
  "issuingCountryCode": "Issuing Country Code",
  "personalNumber": "Personal Number"
]
let defaultObjectsCount = 0
let countryCodes = [
  "ABW": "Aruba",
  "AFG": "Afghanistan",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "ALA": "Åland Islands",
  "AND": "Andorra",
  "ARE": "United Arab Emirates",
  "ASM": "American Samoa",
  "ATA": "Antarctica",
  "AUS": "Australia",
  "AZE": "Azerbaijan",
  "BDI": "Burundi",
  "BEL": "Belgium",
  "BFA": "Burkina Faso",
  "BGD": "Bangladesh",
  "BHR": "Bahrain",
  "BIH": "Bosnia and Herzegovina",
  "BLM": "Saint Barthélemy",
  "BMU": "Bermuda",
  "BOL": "Bolivia, Plurinational State of",
  "BRA": "Brazil",
  "BTN": "Bhutan",
  "BVT": "Bouvet Island",
  "BWA": "Botswana",
  "CAF": "Central African Republic",
  "CCK": "Cocos (Keeling) Islands",
  "CHE": "Switzerland",
  "CIV": "Côte d'Ivoire",
  "CMR": "Cameroon",
  "COD": "Congo, the Democratic Republic of the",
  "CPV": "Cabo Verde",
  "CRI": "Costa Rica",
  "CUB": "Cuba",
  "CXR": "Christmas Island",
  "CYM": "Cayman Islands",
  "CZE": "Czechia",
  "DEU": "Germany",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DNK": "Denmark",
  "DOM": "Dominican Republic",
  "DZA": "Algeria",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "ERI": "Eritrea",
  "ESH": "Western Sahara",
  "ETH": "Ethiopia",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FLK": "Falkland Islands (Malvinas)",
  "FRA": "France",
  "FSM": "Micronesia, Federated States of",
  "GAB": "Gabon",
  "GBR": "United Kingdom",
  "GEO": "Georgia",
  "GGY": "Guernsey",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GLP": "Guadeloupe",
  "GMB": "Gambia",
  "GNB": "Guinea-Bissau",
  "GRC": "Greece",
  "GTM": "Guatemala",
  "GUF": "French Guiana",
  "HKG": "Hong Kong",
  "HMD": "Heard Island and McDonald Islands",
  "HND": "Honduras",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "IDN": "Indonesia",
  "IMN": "Isle of Man",
  "IND": "India",
  "IOT": "British Indian Ocean Territory",
  "IRL": "Ireland",
  "ISL": "Iceland",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JEY": "Jersey",
  "JOR": "Jordan",
  "JPN": "Japan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KIR": "Kiribati",
  "KNA": "Saint Kitts and Nevis",
  "KOR": "Korea, Republic of",
  "KWT": "Kuwait",
  "LAO": "Lao People's Democratic Republic",
  "LBN": "Lebanon",
  "LCA": "Saint Lucia",
  "LIE": "Liechtenstein",
  "LKA": "Sri Lanka",
  "LSO": "Lesotho",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "LVA": "Latvia",
  "MAC": "Macao",
  "MCO": "Monaco",
  "MDA": "Moldova, Republic of",
  "MEX": "Mexico",
  "MHL": "Marshall Islands",
  "MKD": "Macedonia, the former Yugoslav Republic of",
  "MLI": "Mali",
  "MMR": "Myanmar",
  "MNE": "Montenegro",
  "MOZ": "Mozambique",
  "MRT": "Mauritania",
  "MSR": "Montserrat",
  "MTQ": "Martinique",
  "MUS": "Mauritius",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "NAM": "Namibia",
  "NCL": "New Caledonia",
  "NER": "Niger",
  "NFK": "Norfolk Island",
  "NGA": "Nigeria",
  "NIC": "Nicaragua",
  "NLD": "Netherlands",
  "NOR": "Norway",
  "NPL": "Nepal",
  "NRU": "Nauru",
  "NZL": "New Zealand",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PCN": "Pitcairn",
  "PER": "Peru",
  "PHL": "Philippines",
  "PLW": "Palau",
  "PNG": "Papua New Guinea",
  "POL": "Poland",
  "PRI": "Puerto Rico",
  "PSE": "Palestine, State of",
  "PYF": "French Polynesia",
  "QAT": "Qatar",
  "REU": "Réunion",
  "ROU": "Romania",
  "RUS": "Russian Federation",
  "RWA": "Rwanda",
  "SAU": "Saudi Arabia",
  "SDN": "Sudan",
  "SEN": "Senegal",
  "SGP": "Singapore",
  "SHN": "Saint Helena, Ascension and Tristan da Cunha",
  "SJM": "Svalbard and Jan Mayen",
  "SLB": "Solomon Islands",
  "SMR": "San Marino",
  "SOM": "Somalia",
  "SPM": "Saint Pierre and Miquelon",
  "SRB": "Serbia",
  "SSD": "South Sudan",
  "STP": "Sao Tome and Principe",
  "SUR": "Suriname",
  "SVK": "Slovakia",
  "SWE": "Sweden",
  "SXM": "Sint Maarten (Dutch part)",
  "SYC": "Seychelles",
  "TCA": "Turks and Caicos Islands",
  "TGO": "Togo",
  "THA": "Thailand",
  "TJK": "Tajikistan",
  "TKL": "Tokelau",
  "TLS": "Timor-Leste",
  "TON": "Tonga",
  "TTO": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TWN": "Taiwan, Province of China",
  "TZA": "Tanzania, United Republic of",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "UMI": "United States Minor Outlying Islands",
  "URY": "Uruguay",
  "USA": "United States of America",
  "UZB": "Uzbekistan",
  "VAT": "Holy See",
  "VCT": "Saint Vincent and the Grenadines",
  "VEN": "Venezuela, Bolivarian Republic of",
  "VGB": "Virgin Islands, British",
  "VIR": "Virgin Islands, U.S.",
  "VNM": "Viet Nam",
  "VUT": "Vanuatu",
  "WLF": "Wallis and Futuna",
  "WSM": "Samoa",
  "YEM": "Yemen",
  "ZAF": "South Africa",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe",
  "D": "Germany",
  "EUE": "European Union",
  "UNA": "specialized agency of the United Nations",
  "XBA": "African Development Bank",
  "XIM": "African Export–Import Bank",
  "XCC": "Caribbean Community or one of its emissaries",
  "XEC": "Economic Community of West African States",
  "XPO": "International Criminal Police Organization",
  "XOM": "Sovereign Military Order of Malta",
  "XXA": "Stateless person, as per the 1954 Convention Relating to the Status of Stateless Persons"
]
